### ISSUE TITLE
XML的支持

### ISSUE THREAD

**Issue by Lemonjing** [junicorn/conf#1]
## XML的支持已经写好了呀

**Comment by biezhi** [comment]
只写了工具类，没写实现。

**Comment by adar-w** [comment]
这样要对XML有一定的约束吧， 毕竟不像properties文件格式统一。

**Comment by biezhi** [comment]
@adar-w 可以看这个测试https://github.com/junicorn/conf/blob/master/src/test/java/com/junicorn/conf/ReadXmlTest.java

**Comment by adar-w** [comment]
了然。直接通过提供XPATH获取配置数据~

**Comment by adar-w** [comment]
XML这种配置经常用来描述对象数据。 可以考虑对这方面提供支持。
